In [2]:
from geopy.geocoders import ArcGIS

In [3]:
nom=ArcGIS

In [4]:
import numpy
n=numpy.arange(27)

In [5]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.rshape[3,9]

AttributeError: 'numpy.ndarray' object has no attribute 'rshape'

In [7]:
n.reshape[3,9]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [8]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
import cv2

In [11]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [13]:
im_g(0:2,2:4)

SyntaxError: invalid syntax (<ipython-input-13-14d99e793d27>, line 1)

In [14]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [15]:
for i in im_g
print[i]

SyntaxError: invalid syntax (<ipython-input-15-5f8197eedce8>, line 1)

In [16]:
for i in im_g:
print[i]

IndentationError: expected an indented block (<ipython-input-16-347974b202f2>, line 2)

In [17]:
for i in im_g:
    print[i]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [18]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [20]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [21]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
ims=numpy.hstack((im_g,im_g))

In [23]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
ims=numpy.vstack((im_g,im_g,im_g))

In [25]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [26]:
lst=numpy.hsplit(ims,5)

In [27]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]